// TUTORIAL
export const GET_LEADS = "GET_LEADS";
export const DELETE_LEAD = "DELETE_LEAD";
export const ADD_LEAD = "ADD_LEAD";

// FORM
export const ADD_FIELD = "ADD_FIELD";
export const IMPORT_CONFIG = "IMPORT_CONFIG";
export const EXPORT_CONFIG = "EXPORT_CONFIG";
export const SET_NUM_ROWS = "SET_NUM_ROWS";
export const SET_FILE_TYPE = "SET_FILE_TYPE";
export const SET_FILE_NAME = "SET_FILE_NAME";

// COLUMN INPUT
export const SET_DATA_TYPE = "SET_DATA_TYPE";
export const SET_NUM_COLS = "SET_NUM_COLS";

// GENERATE DATA
export const GENERATE_DATA = "GENERATE_DATA";
export const SET_OPTS_INT = "SET_OPS_INT";

// CATEGORICAL DATA
export const SET_CAT_DIST = "SET_CAT_DIST";
export const SET_CAT_NAME = "SET_CAT_NAME";
export const SET_CAT_PROB = "SET_CAT_PROB";
export const ADD_CATEGORY = "ADD_CATEGORY";

// CORRELATION
export const SET_CORRELATION_OPTS = "SET_CORRELATION_OPTS";
export const REMOVE_CORRELATED_COL = "REMOVE_CORRELATED_COL";
